### ISSUE TITLE
Not working on Ocaml 4.08

### ISSUE THREAD

**Issue by diegogub** [jacquev6/hashids-ocaml#1]
Hello,

Noticed it's not working for this version. How hard would it be to make it work?

The following dependencies couldn't be met:
  - hashids -> General >= 0.4.0 -> ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)

Thanks

**Comment by jacquev6** [comment]
Thank you for the report! I was made aware of that a few months ago in https://github.com/ocaml/opam-repository/pull/13895 and procrastinated fixing it.

It just so happens that I have a new project using `General`, so I'll probably make it 4.08-compliant quite soon. Stay tuned.

**Comment by diegogub** [comment]
@jacquev6  thank you

**Comment by jacquev6** [comment]
I've submitted https://github.com/ocaml/opam-repository/pull/14777. A few minutes after it's merged, you should be able to `opam update` and then `opam install hashids` on OCaml 4.08.

**Comment by diegogub** [comment]
amazing, thank you again. Will try now

**Comment by jacquev6** [comment]
Nope, you have to wait until https://github.com/ocaml/opam-repository/pull/14777 is merged. That's how OPAM package management works :)

**Comment by diegogub** [comment]
hehe yes, noticed..First timer with OPAM  📦

**Comment by jacquev6** [comment]
So, now it should be working. Don't forget to `opam update` before trying to `opam install hashids`. Please let me know if it works for you so that I can close this issue.

**Comment by diegogub** [comment]
Everything working now, thank you! @jacquev6
